#bpmnrepo:
 # security:
  #  usercontext:
 #     email_claim: https://flowsquad.io/email

# Logging Configurations
logging:
  level:
    io:
      bpmnrepo:
        backend: DEBUG

# Show message error messages in console/response
server:
  error:
    include-message: always
  port: 8080

# Security Configurations
#auth0:
 # audience: https://flowsquad.io

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 150MB
      file-size-threshold: 100MB
    #  security:
 #   oauth2:
  #    resourceserver:
   #     jwt:
    #      issuer-uri: https://flowsquad.eu.auth0.com/

  # Active Profile
 # profiles:
  #  active: no-security

  # Database Configurations
  datasource:
    url: "jdbc:mysql://localhost:3306/bpmnrepo_db"
    username: "root"
    password: "password"
    platform: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        use_sql_comments: true
        ddl-auto: update
    generate-ddl: true
  flyway:
    enabled: false


security.basic.enable: false

# Swagger Configurations
springdoc:
  swagger-ui:
    path=/swagger-ui: /swagger-ui

