bpmnrepo:
  security:
    usercontext:
      email_claim: https://flowsquad.io/email

# Logging Configurations
logging:
  level:
    io:
      bpmnrepo:
        backend: DEBUG

# Show message error messages in console/response
server:
  error:
    include-message: always
  port: 8081

# Security Configurations
auth0:
  audience: 3h8eEHlAfoMF4yYkTOzsDcQc6rgpLOxO

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://flowsquad.eu.auth0.com/

  # Active Profile
 # profiles:
  #  active: no-security

  # Database Configurations
  datasource:
    url: "jdbc:postgresql://localhost:5432/bpmnrepo_db_postgres"
    username: "keycloak"
    password: "password"
    platform: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        use_sql_comments: true
        ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
  flyway:
    enabled: false


security.basic.enable: false

# Swagger Configurations
springdoc:
  swagger-ui:
    path=/swagger-ui: /swagger-ui

