spring:
  application.name: @project.artifactId@

  # Spring data rest
  data:
    rest:
      # Definition of page size for PagingAndSortingRepository
      max-page-size: 0x7fffffff
      default-page-size: 0x7fffffff
      return-body-on-update: true
      return-body-on-create: true

  datasource:
    driver-class-name: org.postgresql.Driver
  # Spring JPA
  h2.console.enabled: true
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # Logging for database operation
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# Define the keycloak development realm here
realm: ${SSO_REALM}

security:
  # possible values: none, all, changing (With changing, only changing requests such as POST, PUT, DELETE are logged)
  logging.requests: all
  oauth2:
    resource:
      jwk:
        key-set-uri: ${SSO_ISSUER_URL}/protocol/openid-connect/certs
      user-info-uri: ${SSO_ISSUER_URL}/protocol/openid-connect/userinfo
      prefer-token-info: false
    client:
      client-id: bpm-server

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 39146
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false

# Config for spring actuator endpoints
management:
  server.port: ${server.port}
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, prometheus
      path-mapping:
        prometheus: metrics
  endpoint:
    health.enabled: true
    info.enabled: true
    prometheus.enabled: true
info.application.name: @project.artifactId@
info.application.version: @project.version@

digiwf:
  deployment:
    targets: "DEV, TEST, DEMO, PROCESSESTEST, PROCESSESDEMO, PROCESSESHOTFIX"
