name: release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Publish
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_SNAPSHOT: false
          ORG_GRADLE_PROJECT_signingKey: ${{secrets.PGP_PRIVATE_KEY}}
          ORG_GRADLE_PROJECT_signingPassword: ${{secrets.PGP_PRIVATE_KEY_SECRET}}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.NEXUS_PASSWORD }}
